[project]
name = "funscript-flow"
version = "1.0.0"
description = "Computer vision-based automatic funscript generation"
requires-python = ">=3.13"
dependencies = [
    "numpy",
    "opencv-python",
    "PySide6",
    "matplotlib",
]

[project.optional-dependencies]
build = ["nuitka", "imageio"]